# GitHub Pages Configuration Variables
remote_theme: nikahmadz/prime.dev@v0.1.4-beta

# The title of your site
title: Base

# A short description of your site's purpose
description: Web Application Framework
