# GitHub Pages Configuration Variables

# The theme of your site
remote_theme: nikahmadz/pages@v0.1.5-beta

# The title of your site
title: Base

# A short description of your site's purpose
description: Web Application Framework
